version: "3.8"

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus-exam.yml:/etc/prometheus/prometheus.yml
      - ./alert-rules-exam.yml:/etc/prometheus/alert-rules-exam.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    depends_on:
      - blackbox_exporter
      - alertmanager

  blackbox_exporter:
    image: prom/blackbox-exporter
    container_name: blackbox_exporter
    ports:
      - "9115:9115"

  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ./alertmanager-exam.yml:/etc/alertmanager/alertmanager.yml
    command:
      - "--config.file=/etc/alertmanager/alertmanager.yml"